//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateFinder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Day")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHA1")]
        public string Hash {
            get {
                return ((string)(this["Hash"]));
            }
            set {
                this["Hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color FormBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FormBackColor"]));
            }
            set {
                this["FormBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54, 79, 123")]
        public global::System.Drawing.Color PanelTopColor {
            get {
                return ((global::System.Drawing.Color)(this["PanelTopColor"]));
            }
            set {
                this["PanelTopColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 34, 41")]
        public global::System.Drawing.Color PanelLogoColor {
            get {
                return ((global::System.Drawing.Color)(this["PanelLogoColor"]));
            }
            set {
                this["PanelLogoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 75, 97")]
        public global::System.Drawing.Color PanelLeftMenuColor {
            get {
                return ((global::System.Drawing.Color)(this["PanelLeftMenuColor"]));
            }
            set {
                this["PanelLeftMenuColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 75, 97")]
        public global::System.Drawing.Color ButtonFileColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonFileColor"]));
            }
            set {
                this["ButtonFileColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 75, 97")]
        public global::System.Drawing.Color ButtonPartitionColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonPartitionColor"]));
            }
            set {
                this["ButtonPartitionColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 75, 97")]
        public global::System.Drawing.Color ButtonSettingsColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonSettingsColor"]));
            }
            set {
                this["ButtonSettingsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 75, 97")]
        public global::System.Drawing.Color ButtonAboutColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonAboutColor"]));
            }
            set {
                this["ButtonAboutColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 75, 97")]
        public global::System.Drawing.Color PanelFileColor {
            get {
                return ((global::System.Drawing.Color)(this["PanelFileColor"]));
            }
            set {
                this["PanelFileColor"] = value;
            }
        }
    }
}
